### ISSUE TITLE
xd-ing into directory names that contain spaces

### ISSUE THREAD

**Issue by tmancill** [fbb-git/xd#1]
When I attempt to `xd` into a directory name that contains a space, the `cd` is only passed the path up to the space.  (And no, I wouldn't personally create a directory with a space in the name, but the software I'm using does...)  

I was using the recommended bash function in my .bashrc:

``` bash
xd () {
    cd `/usr/bin/xd -g $*`
}
```

Modifying the function to quote output of `xd` resolved the issue for me:

``` bash
xd () {
    cd "`/usr/bin/xd -g $*`"
}
```

**Comment by fbb-git** [comment]
Dear tmancill, you wrote:

> When I attempt to `xd` into a directory name that contains a space, the `cd`
> is only passed the path up to the space.  (And no, I wouldn't personally
> create a directory with a space in the name, but the software I'm using
> does...)  

I'm tempted to reply with a `shit happens', but I won't ;-)

> I was using the recommended bash function in my .bashrc:
> 
> ``` bash
> xd () {
>     cd `/usr/bin/xd -g $*`
> }
> ```
> 
> Modifying the function to quote output of `xd` resolved the issue for me:
> 
> ``` bash
> xd () {
>     cd "`/usr/bin/xd -g $*`"
> }
> ```

Of course, thanks for the notification and for the fix you offered. I''ll
adopt it in xd's next release.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Hi tmancill,

Release 3.24.00/3.24.01 fixes the issue: the man-pages shows the modified scripts that can handle blanks in directory names for bash and tcsh shells.

Cheers,
F.
